# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "keyless-workflow-demo"
    dynamodb_table = "tflocks"
    encrypt        = true
    key            = "keyless-workflow-demo/terraform.tfstate"
    region         = "us-west-2"
  }
}
